DEFAULTS = {
    "editing": {"pace": "normal", "editorial_quality_warnings": False},
    "branding": {"end_tag": {"enabled": False}},
    "video": {"width": 1080, "height": 1920, "fps_mode": "source", "preset": "medium", "crf": 20,
              "reframe": {"mode": "center_crop", "strict": False, "zoom": 1.0, "manual_x": None, "manual_y": None}},
    "audio": {"normalize": True, "target_lufs": -16, "true_peak": -1.5,
              "source_audio": {"mode": "duck", "duck_db": -16}},
    "voice": {"engine": "piper", "voice_id": "pt_BR-faber-medium", "voice": None, "rate": 1.0, "volume": 1.0},
    "captions": {"enabled": True, "mode": "narration", "source_dialogue": False, "whisper_model": "small",
                 "max_lines": 2, "max_chars_per_line": 34, "position": "bottom", "margin_bottom": 230,
                 "style": {"font_family": "Arial", "font_size": 64, "font_weight": "bold", "font_color": "#FFFFFF",
                           "outline_color": "#000000", "outline_width": 4, "background_enabled": False}},
    "hook": {"enabled": True, "duration": 2.2, "position": "top", "margin_top": 165,
             "style": {"font_family": "Arial", "font_size": 76, "font_color": "#FFFFFF", "outline_color": "#000000", "outline_width": 5}},
    "source_label": {"enabled": True, "show_last_seconds": 2, "position": "bottom", "margin_bottom": 90},
    "transition": {"type": "cut", "duration": .15},
    "export": {"filename_template": "{index:02d}-{slug}-{id}.mp4", "audio_bitrate": "192k", "faststart": True,
               "write_metadata_sidecar": True},
    "transformative_gate": {"enabled": True, "warn_if_no_voiceover": True,
                           "warn_continuous_source_clip_over_seconds": 25, "warn_if_original_words_below": 20},
}
